openapi: "3.0.3"
info:
  title: Лабораторная работа №1
  version: "1.0"
servers:
  - url: https://api.server.test/v1

paths:
  /bars/discipline/{discipline-id}/labwork/{labwork-id}/add:
    post:
      description: "Добавить лабораторную работу в программу дисциплины"
      parameters:
        - name: discipline-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: labwork-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: "Лабораторная работа добавлена в программу дисциплины"
        "400":
          description: "Некорректный id"
        "404":
          description: "Дисциплина или лабораторная работа не найдена"

  /bars/discipline/{discipline-id}/labwork/{labwork-id}/remove:
    delete:
      description: "Удалить лабораторную работу из программы дисциплины"
      parameters:
        - name: discipline-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: labwork-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "204":
          description: "Лабораторная работа удалена из программы дисциплины"
        "400":
          description: "Некорректный id"
        "404":
          description: "Дисциплина или лабораторная работа не найдена"
