openapi: "3.0.3"
info:
  title: Лабораторная работа №1
  version: "1.0"
servers:
  - url: https://176.12.70.243:8081

paths:
  /bars/discipline/{discipline-id}/labwork/{labwork-id}/add:
    post:
      description: "Добавить лабораторную работу в программу дисциплины"
      parameters:
        - name: discipline-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: labwork-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: "Лабораторная работа добавлена в программу дисциплины"
        "400":
          description: "Некорректный id"
        "404":
          description: "Дисциплина или лабораторная работа не найдена"

  /bars/discipline/{discipline-id}/labwork/{labwork-id}/remove:
    delete:
      description: "Удалить лабораторную работу из программы дисциплины"
      parameters:
        - name: discipline-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: labwork-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "204":
          description: "Лабораторная работа удалена из программы дисциплины"
        "400":
          description: "Некорректный id"
        "404":
          description: "Дисциплина или лабораторная работа не найдена"

components:
  schemas:
    LabWork:
      type: object
      required:
        - id
        - name
        - coordinates
        - creationDate
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          readOnly: true

        name:
          type: string
          minLength: 1

        coordinates:
          $ref: "#/components/schemas/Coordinates"

        creationDate:
          type: string
          format: date-time
          readOnly: true

        minimalPoint:
          type: integer
          format: int32
          minimum: 0
          exclusiveMinimum: true

        difficulty:
          type: string
          nullable: true
          enum: [VERY_EASY, EASY, VERY_HARD, TERRIBLE]

        discipline:
          allOf:
            - $ref: "#/components/schemas/Discipline"
          nullable: true

    Coordinates:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: integer
          format: int32
        y:
          type: number
          format: double

    Discipline:
      type: object
      required:
        - name
        - labsCount
      properties:
        name:
          type: string
          minLength: 1
        practiceHours:
          type: integer
          format: int64
        labsCount:
          type: integer
          format: int64

    Group:
      type: object
      required:
        - name
        - count
      properties:
        name:
          type: string
        count:
          type: integer
          format: int64
          minimum: 1
